const tintColor = "#4f46e5";

export const Theme = {
  colors: {
    title: "#000",
    description: "#09090b",
    error: "#ef4444",
    background: "#fff",
    mainColor: tintColor,
    icon: "#687076",
    tabIconDefault: "#687076",
    white: "#fff",
    black: "#000",
  },
  fonts: {
    thin: "Poppins_100Thin",
    thinItalic: "Poppins_100Thin_Italic",
    extraLight: "Poppins_200ExtraLight",
    extraLightItalic: "Poppins_200ExtraLight_Italic",
    light: "Poppins_300Light",
    lightItalic: "Poppins_300Light_Italic",
    regular: "Poppins_400Regular",
    regularItalic: "Poppins_400Regular_Italic",
    medium: "Poppins_500Medium",
    mediumItalic: "Poppins_500Medium_Italic",
    semiBold: "Poppins_600SemiBold",
    semiBoldItalic: "Poppins_600SemiBold_Italic",
    bold: "Poppins_700Bold",
    boldItalic: "Poppins_700Bold_Italic",
    extraBold: "Poppins_800ExtraBold",
    extraBoldItalic: "Poppins_800ExtraBold_Italic",
    black: "Poppins_900Black",
    blackItalic: "Poppins_900Black_Italic",
  },
};
